CREATE PLUGGABLE DATABASE e_27406_shyaka_inventory_db
  ADMIN USER shyaka IDENTIFIED BY shyaka
  FILE_NAME_CONVERT = (
    'C:\ORCL\ORADATA\ORCL\PDBSEED\', 
    'C:\ORCL\ORADATA\ORCL\E_27406_SHYAKA_INVENTORY_DB\'
  );
